### ISSUE TITLE
Collision solving with c2Poly

### ISSUE THREAD

**Issue by sro5h** [RandyGaul/tinyheaders#36] opened 2017-06-20 17:25 UTC
I can't figure out how I am supposed to correctly resolve a collision between a `c2Poly` and a `c2Circle`.
For `c2Circle` vs `c2AABB` the following code worked:
```c++
c2CircletoAABBManifold(circle, aabb, &manifold);
circle.p.x += manifold.normal.x * manifold.depths[0];
circle.p.y += manifold.normal.y * manifold.depths[0];
```
Everything works as I expect and there is no 'jitter' when moving along the edges of the `c2AABB`. The same code also works for `c2AABB` vs `c2Poly` (except the problem below).

However if I do the same with the `c2Poly` (Note that I also have to substract this time):
```c++
c2CircletoPolyManifold(circle, poly, &manifold);
circle.p.x -= manifold.normal.x * manifold.depths[0];
circle.p.y -= manifold.normal.y * manifold.depths[0];
```
Then the `c2Circle` 'jumps' off the edges of the `c2Poly` (Using a `c2AABB` instead it works though):
![peek 2017-06-20 19-21](https://user-images.githubusercontent.com/17962301/27346505-c00473be-55ed-11e7-91d8-fa5309908f6f.gif)

Using just:
```c++
circle.p.x -= manifold.normal.x;
circle.p.y -= manifold.normal.y;
```
Works better but the movement of the `c2Circle` is 'jittery' along angled edges of the `c2Poly` (difficult to see in the recording).
![peek 2017-06-20 19-23](https://user-images.githubusercontent.com/17962301/27346586-fcf833a0-55ed-11e7-9722-222688bf2917.gif)

Furthermore the `c2AABB` will jump around if one of its edges is moved towards a corner of the `c2Poly`:
![peek 2017-06-20 19-18](https://user-images.githubusercontent.com/17962301/27346370-4553a86a-55ed-11e7-8511-b72566565d85.gif)

Used `c2Poly`:
```c++
poly.count = 4;
poly.verts[0] = c2V(30, 30);
poly.verts[1] = c2V(130, 40);
poly.verts[2] = c2V(100, 80);
poly.verts[3] = c2V(40, 60);
c2MakePoly(&poly);
```

**Comment by RandyGaul** [comment] 2017-06-20 18:03
The way to solve these kinds of problems is to render the manifold. Render the contact points, and draw a line along the normal scaled by the penetration depth. Center and draw this line upon each contact point. Disable the code that resolves collisions. Move the shapes together and find a configuration that gives you trouble.

If you see a manifold that does not make sense, after rending it, post it up here.

**Comment by sro5h** [comment] 2017-06-20 18:34
Ok it renders each contact point and draws a line from 'contact point' to 'contact point + normal * depth' (I guess thats what you meant). This is what causes the circle to jump: 
![manifold_big](https://user-images.githubusercontent.com/17962301/27349509-c80b5316-55f7-11e7-8462-e345b2f3296c.gif)
The normal gets smaller the deeper the circle goes into the polygon, from my understanding that should be the oposite.

**Comment by RandyGaul** [comment] 2017-06-20 18:39
That is definitely incorrect! I'm fixing that now. Thanks for the rendering. Make sure to render any other problem cases you find, and I can quickly tell you if there's a bug.

**Comment by RandyGaul** [comment] 2017-06-20 18:45
I pushed a fix for c2CircletoPolyManifold. I'm having trouble finding a bug involving AABB and poly though.

The thing about the collision normal, is if there are no bugs, the manifold normal should always point from shape A to shape B. A is the shape in the first parameter, and B is the shape in the second parameter. I am guessing in your AABB to poly gif, you have the normal flipped.

**Comment by sro5h** [comment] 2017-06-20 18:47
I am testing the aabb case with the rendering right now, ill comment if I can find something.

Ill keep that in mind while testing, thanks for the fix gonna test it too :)

**Comment by sro5h** [comment] 2017-06-20 18:55
I think I found the problem with c2AABB. The normal changes from facing towards the aabb to facing to the opposite direction if I move over a corner of the polygon. That causes the aabb to jump towards the other side of the polygon:
![change_dir](https://user-images.githubusercontent.com/17962301/27350500-ce09a21a-55fa-11e7-983b-653e067b1dee.gif)

**Comment by RandyGaul** [comment] 2017-06-20 18:56
Aaah. Yep. Inconsistent normal direction. I'll get out a fix for that soon. Thanks for gif. I'll add you as a contributor too!

**Comment by sro5h** [comment] 2017-06-20 18:57
Thanks :D I'll keep playing around with it. Gonna post again if I find something

**Comment by RandyGaul** [comment] 2017-06-20 19:04
Pushed attempted fix for `c2PolytoPolyManifold`. Let me know if you still have troubles! Ganna close this issue out for now, but feel free to comment more.

**Closed by RandyGaul** 2017-06-20 19:04 UTC

**Comment by sro5h** [comment] 2017-06-20 19:44
I don't know, the normals still look odd, but if I try to solve the collision everything works as expected. Gif of the normals:
![normals_odd](https://user-images.githubusercontent.com/17962301/27352623-a22c2ed6-5601-11e7-97a6-e7af118bf528.gif)

**Comment by RandyGaul** [comment] 2017-06-20 20:11
Looks like a bug in your manifold rendering? I'm not able to reproduce anything like that with my draw function:

	void DrawManifold( c2Manifold m )
	{
		c2v n = m.normal;
		tgLineColor( ctx, 1.0f, 0.2f, 0.4f );
		for ( int i = 0; i < m.count; ++i )
		{
			c2v p = m.contact_points[ i ];
			float d = m.depths[ i ];
			DrawCircle( p, 3.0f );
			tgLine( ctx, p.x, p.y, 0, p.x + n.x * d, p.y + n.y * d, 0 );
		}
	}

**Comment by sro5h** [comment] 2017-06-20 20:46
I adjusted my function:
```c++
c2v n = manifold.normal;                                    
for (int i = 0; i < manifold.count; ++i) {
           c2v p = manifold.contact_points[i];
           float d = manifold.depths[i];
           n.x = n.x * d;
           n.y = n.y * d;
 
           // The line
           draw(p, c2Add(p, n));
           // The point
           draw(p, sf::Color::Red);
}
```
Now I get:
![manifold_render](https://user-images.githubusercontent.com/17962301/27355095-06e78fe8-560a-11e7-911d-85159765e016.gif)

But its late and Im tired so I could be missing something obvious :)

**Comment by RandyGaul** [comment] 2017-06-20 20:50
If you'd like me to take a look, post a snapshot each shape. Just dump the floats out in a console or something so I can see the verts/normals. I'll copy paste it into my testbed and see what's up.

**Comment by sro5h** [comment] 2017-06-20 20:54
```c++
// Create aabb
c2AABB aabb;
aabb.min = c2V(150, 150);
aabb.max = c2V(200, 200);

// Create polygon
c2Poly poly;
poly.count = 4;
poly.verts[0] = c2V(30, 30);
poly.verts[1] = c2V(130, 40);
poly.verts[2] = c2V(100, 80);
poly.verts[3] = c2V(40, 60);
```

I also created a [repo](https://github.com/sro5h/tinyc2-tests.git) and pushed two of my tests as branches :)

**Comment by RandyGaul** [comment] 2017-06-20 20:55
Are those the exact positions where they are intersecting, that you want me to look at?

**Comment by sro5h** [comment] 2017-06-20 20:58
No but here you go (poly the same):
```c++
aabb.min = c2V(50, 50);
aabb.max = c2V(90, 90);
```

My result:
![screenshot from 2017-06-20 22-58-16](https://user-images.githubusercontent.com/17962301/27355616-fb2772a2-560b-11e7-9b04-47c1e0885bb8.png)

**Comment by RandyGaul** [comment] 2017-06-20 21:03
c2Poly poly;
        poly.count = 4;
        poly.verts[0] = c2V(30, 30);
        poly.verts[1] = c2V(130, 40);
        poly.verts[2] = c2V(100, 80);
        poly.verts[3] = c2V(40, 60);
        c2MakePoly( &poly );

        c2AABB aabb;
        aabb.min = c2V(50, 50);
        aabb.max = c2V(90, 90);

        tgLineColor( ctx, 1.0f, 1.0f, 1.0f );
        DrawPoly( poly.verts, poly.count );
        DrawAABB( aabb.min, aabb.max );

        c2Manifold m;
        c2AABBtoPolyManifold( aabb, &poly, 0, &m );

        if ( m.count )
        {
            DrawManifold( m );
        }

Gives me:

![image](https://user-images.githubusercontent.com/1919825/27355818-313ead56-55c1-11e7-82da-c62fdb48d8d3.png)

Which looks correct. Normal points from AABB to poly, and the manifold depths look correct.

**Comment by RandyGaul** [comment] 2017-06-20 21:10
Oh BTW the bug in your code is that your for loop scales the normal each time it runs (just noticed). Try this:

```c++                                
for (int i = 0; i < manifold.count; ++i) {
           c2v n = manifold.normal;    
           c2v p = manifold.contact_points[i];
           float d = manifold.depths[i];
           n.x = n.x * d;
           n.y = n.y * d;
 
           // The line
           draw(p, c2Add(p, n));
           // The point
           draw(p, sf::Color::Red);
}
```

**Comment by sro5h** [comment] 2017-06-20 21:17
Ohhhh... well yes now it shows the same. One last question though:
Why does the normal direction change from the aabb position I gave you to:
```c++
aabb.min = c2V(70, 50);
aabb.max = c2V(110, 90);
```
Old Pos:
![pos1](https://user-images.githubusercontent.com/17962301/27356413-a3d91f8e-560e-11e7-92eb-d106da3c64c5.png)

New Pos:
![pos2](https://user-images.githubusercontent.com/17962301/27356374-80eb69b4-560e-11e7-8e9f-9f1864bc75b4.png)

**Comment by RandyGaul** [comment] 2017-06-20 21:20
The normal will always point along the axis of minimum penetration. In the top picture, the normals are pointing along the shortest distance to resolve the collision. As the shapes move deeper into each other and the vertex start hitting the AABB, the axis shifts. Since the axis of minimum penetration shifted, so does the normal; it points along the new direction for the shortest distance to resolve in the bottom picture.

For games, just trusting the manifold contents and performing some kind of collision resolution with disregard to shifting normals should look quite good during gameplay :)

**Comment by sro5h** [comment] 2017-06-20 21:22
Ohhh... Thank you, got it.
Sorry about the confusion I meant to write this:
One last question though:
Why does the position of the contact points change if I move the aabb so it is over the polygon edge?:
```c++
aabb.min = c2V(70, 50);
aabb.max = c2V(110, 90);
```
Old pos:
![pos1](https://user-images.githubusercontent.com/17962301/27356536-19c39774-560f-11e7-909c-1b92848e4a1d.png)

New Pos
![pos2](https://user-images.githubusercontent.com/17962301/27356585-50c5fc8a-560f-11e7-9a3e-d0037e7d5261.png)

**Comment by RandyGaul** [comment] 2017-06-20 21:23
The axis of minimum penetration used to sit on the polygon in the first picture. The internal algorithm clips the face on the *other* shape, against the shape the axis belongs to.

In the bottom picture the axis sits on the AABB, and a shape on the polygon gets clipped.

**Comment by RandyGaul** [comment] 2017-06-20 21:26
These are the faces defining the axis in each picture:

![image](https://user-images.githubusercontent.com/1919825/27356713-6df1165a-55c4-11e7-845d-c43d6fa1655a.png)

**Comment by sro5h** [comment] 2017-06-20 21:27
Ok makes sense now. I really appreciate your help and near instantaneous fixes

**Comment by RandyGaul** [comment] 2017-06-20 21:28
No problem! :)

**Comment by sro5h** [comment] 2017-06-22 07:55
I just noticed that if a `c2Circle`'s center is over an edge of a `c2Poly`, then the depth gets very close to 0 and then starts to get bigger again:
![depth_zero](https://user-images.githubusercontent.com/17962301/27422836-e8b7147c-572f-11e7-8cc0-20dded7fc1e0.gif)

I changed line 1400 to:
```c++
m->depths[ 0 ] = sep - A.r;
```
You something similar in case the circles center is outside the polygon so I guess it has to be done here aswell. Then the normal looks much better (at least I think it does):
![better_fix](https://user-images.githubusercontent.com/17962301/27423127-e51eaf40-5730-11e7-94f2-30bd80a1c2a3.gif)

**Comment by RandyGaul** [comment] 2017-06-22 18:00
These are very good bugfixes. I am impressed! Please make a pull request with these fixes. I'm very busy this week, and cannot be as responsive as I was :)

The normals in your fixed version look exactly like what I intended. Lets get this into tinyc2 asap.

**Comment by sro5h** [comment] 2017-06-22 19:43
Thanks :) I'll send the pull request.
The depth should always be positive, right? Because only the normal should indicate the direction

**Comment by RandyGaul** [comment] 2017-06-22 19:44
Yes depth should remain consistently positive.
